BirdEyeRemapper: main.cpp 
	g++  -std=c++11 -g  -o BirdEyeRemapper   `pkg-config --cflags opencv`  main.cpp /usr/local/lib/libOmnidirectionalCamera.so  /usr/local/lib/libCudaOmnidirectionalCamera.so  `pkg-config --libs opencv`
clean: 
	rm BirdEyeRemapper
